[app]
name = "restful-api-demo"
host = "0.0.0.0"
port = "8080"
key  = "this is your app key"

[mysql]
host = "101.35.79.218"
port = "3306"
username = "root"
password = "123456"
database = "test"


[log]
level = "debug"
format = "text"
to = "stdout"